const TRANSLATIONS: Record<string, string> = {
  // América del Sur
  "Argentina":           "Argentina",
  "Brazil":              "Brasil",
  "Uruguay":             "Uruguay",
  "Colombia":            "Colombia",
  "Chile":               "Chile",
  "Peru":                "Perú",
  "Ecuador":             "Ecuador",
  "Paraguay":            "Paraguay",
  "Bolivia":             "Bolivia",
  "Venezuela":           "Venezuela",

  // América del Norte y Central
  "United States":       "Estados Unidos",
  "Mexico":              "México",
  "Canada":              "Canadá",
  "Costa Rica":          "Costa Rica",
  "Panama":              "Panamá",
  "Honduras":            "Honduras",
  "Guatemala":           "Guatemala",
  "El Salvador":         "El Salvador",
  "Jamaica":             "Jamaica",
  "Trinidad and Tobago": "Trinidad y Tobago",
  "Haiti":               "Haití",
  "Cuba":                "Cuba",

  // Europa
  "Spain":               "España",
  "France":              "Francia",
  "Germany":             "Alemania",
  "England":             "Inglaterra",
  "Portugal":            "Portugal",
  "Netherlands":         "Países Bajos",
  "Belgium":             "Bélgica",
  "Italy":               "Italia",
  "Croatia":             "Croacia",
  "Switzerland":         "Suiza",
  "Denmark":             "Dinamarca",
  "Sweden":              "Suecia",
  "Norway":              "Noruega",
  "Poland":              "Polonia",
  "Turkey":              "Turquía",
  "Ukraine":             "Ucrania",
  "Austria":             "Austria",
  "Hungary":             "Hungría",
  "Czech Republic":      "República Checa",
  "Czechia":             "República Checa",
  "Slovakia":            "Eslovaquia",
  "Slovenia":            "Eslovenia",
  "Romania":             "Rumanía",
  "Serbia":              "Serbia",
  "Greece":              "Grecia",
  "Scotland":            "Escocia",
  "Wales":               "Gales",
  "Ireland":             "Irlanda",
  "Republic of Ireland": "Irlanda",
  "Northern Ireland":    "Irlanda del Norte",
  "Russia":              "Rusia",
  "Albania":             "Albania",
  "Bulgaria":            "Bulgaria",
  "North Macedonia":     "Macedonia del Norte",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  "Montenegro":          "Montenegro",
  "Kosovo":              "Kosovo",
  "Georgia":             "Georgia",
  "Armenia":             "Armenia",
  "Azerbaijan":          "Azerbaiyán",
  "Kazakhstan":          "Kazajistán",
  "Iceland":             "Islandia",
  "Finland":             "Finlandia",
  "Belarus":             "Bielorrusia",
  "Latvia":              "Letonia",
  "Lithuania":           "Lituania",
  "Estonia":             "Estonia",
  "Moldova":             "Moldavia",
  "Luxembourg":          "Luxemburgo",
  "Cyprus":              "Chipre",
  "Malta":               "Malta",

  // África
  "Morocco":             "Marruecos",
  "Senegal":             "Senegal",
  "Egypt":               "Egipto",
  "Nigeria":             "Nigeria",
  "Cameroon":            "Camerún",
  "Ghana":               "Ghana",
  "Ivory Coast":         "Costa de Marfil",
  "Côte d'Ivoire":       "Costa de Marfil",
  "Tunisia":             "Túnez",
  "Algeria":             "Argelia",
  "South Africa":        "Sudáfrica",
  "Mali":                "Malí",
  "Burkina Faso":        "Burkina Faso",
  "Guinea":              "Guinea",
  "Kenya":               "Kenia",
  "Tanzania":            "Tanzania",
  "Uganda":              "Uganda",
  "Rwanda":              "Ruanda",
  "Ethiopia":            "Etiopía",
  "Angola":              "Angola",
  "Mozambique":          "Mozambique",
  "Zambia":              "Zambia",
  "Zimbabwe":            "Zimbabue",
  "Madagascar":          "Madagascar",
  "Gabon":               "Gabón",
  "Cape Verde":          "Cabo Verde",
  "Cape Verde Islands":  "Cabo Verde",
  "DR Congo":            "Rep. Dem. del Congo",
  "Congo DR":            "Rep. Dem. del Congo",
  "Congo":               "Congo",
  "Sudan":               "Sudán",
  "Libya":               "Libia",
  "Namibia":             "Namibia",
  "Benin":               "Benín",
  "Togo":                "Togo",
  "Gambia":              "Gambia",
  "Comoros":             "Comoras",
  "Malawi":              "Malaui",
  "Guinea-Bissau":       "Guinea-Bisáu",
  "Equatorial Guinea":   "Guinea Ecuatorial",
  "Mauritania":          "Mauritania",
  "Lesotho":             "Lesoto",
  "Eswatini":            "Esuatini",
  "Botswana":            "Botsuana",

  // Asia
  "Japan":               "Japón",
  "South Korea":         "Corea del Sur",
  "Korea Republic":      "Corea del Sur",
  "Iran":                "Irán",
  "Saudi Arabia":        "Arabia Saudita",
  "Australia":           "Australia",
  "Qatar":               "Catar",
  "China":               "China",
  "Indonesia":           "Indonesia",
  "India":               "India",
  "Iraq":                "Irak",
  "Uzbekistan":          "Uzbekistán",
  "Jordan":              "Jordania",
  "Oman":                "Omán",
  "Bahrain":             "Baréin",
  "UAE":                 "Emiratos Árabes Unidos",
  "United Arab Emirates":"Emiratos Árabes Unidos",
  "Syria":               "Siria",
  "Palestine":           "Palestina",
  "Lebanon":             "Líbano",
  "Vietnam":             "Vietnam",
  "Thailand":            "Tailandia",
  "Philippines":         "Filipinas",
  "Malaysia":            "Malasia",
  "Kyrgyzstan":          "Kirguistán",
  "Tajikistan":          "Tayikistán",
  "Turkmenistan":        "Turkmenistán",
  "Myanmar":             "Myanmar",
  "Singapore":           "Singapur",
  "New Zealand":         "Nueva Zelanda",
};

export function teamName(name: string): string {
  return TRANSLATIONS[name] ?? name;
}
